name: Release Preview Nuget Package

on:
  push:
    branches: [ dev ]

jobs:
  release-preview:
   if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
   runs-on: ubuntu-latest

   steps:
   - uses: actions/checkout@v4
   - uses: benjlevesque/short-sha@v2.2
     id: short-sha
   - name: Setup .NET
     uses: actions/setup-dotnet@v3
     with:
        dotnet-version: 8.0.x
   - name: Restore dependencies
     run: dotnet restore
   - name: Build TwitchLib.EventSub.Websockets
     run: dotnet build -c Release --no-restore
   - name: Pack TwitchLib.EventSub.Websockets
     run: dotnet pack ./TwitchLib.EventSub.Websockets/TwitchLib.EventSub.Websockets.csproj -v normal -c Release -o nugets --no-build --version-suffix "preview-${{ steps.short-sha.outputs.sha }}"
   - name: Push to Nuget
     run: dotnet nuget push "./nugets/*.nupkg" -k ${{ secrets.API_NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json
